import type { OrderServiceType } from "@/lib/constants/orders";
import type { ServiceDetailDisplayField } from "./admin-order-service-details.types";

export const SERVICE_DETAIL_DISPLAY: Record<
  OrderServiceType,
  ServiceDetailDisplayField[]
> = {
  regular_cleaning: [
    { key: "propertySizeM2", label: "Property size (m²)", category: "pricing", valueType: "number" },
    { key: "cleaningIntensity", label: "Cleaning intensity", category: "pricing", valueType: "string" },
    { key: "roomsCount", label: "Rooms", category: "cleaner", valueType: "number" },
    { key: "bedroomsCount", label: "Bedrooms", category: "cleaner", valueType: "number" },
    { key: "bathroomsCount", label: "Bathrooms", category: "cleaner", valueType: "number" },
    { key: "kitchenIncluded", label: "Kitchen", category: "cleaner", valueType: "boolean" },
    { key: "livingRoomIncluded", label: "Living room", category: "cleaner", valueType: "boolean" },
    { key: "corridorIncluded", label: "Corridor", category: "cleaner", valueType: "boolean" },
    { key: "balconyIncluded", label: "Balcony", category: "pricing", valueType: "boolean" },
    { key: "fridgeCleaning", label: "Fridge cleaning", category: "pricing", valueType: "boolean" },
    { key: "ovenCleaning", label: "Oven cleaning", category: "pricing", valueType: "boolean" },
    { key: "insideCabinets", label: "Inside cabinets", category: "pricing", valueType: "boolean" },
    { key: "windowsInside", label: "Windows (inside)", category: "pricing", valueType: "boolean" },
    { key: "hasPets", label: "Pets on site", category: "pricing", valueType: "boolean" },
    { key: "petType", label: "Pet type", category: "cleaner", valueType: "string" },
    { key: "extraHours", label: "Extra hours", category: "pricing", valueType: "number" },
    { key: "suppliesProvidedBy", label: "Supplies provided by", category: "cleaner", valueType: "string" },
    { key: "equipmentRequired", label: "Equipment required", category: "cleaner", valueType: "stringArray" },
  ],
  move_in_out: [
    { key: "propertySizeM2", label: "Property size (m²)", category: "pricing", valueType: "number" },
    { key: "packageType", label: "Package", category: "pricing", valueType: "string" },
    { key: "isMoveIn", label: "Move in", category: "general", valueType: "boolean" },
    { key: "isMoveOut", label: "Move out", category: "general", valueType: "boolean" },
    { key: "emptyApartment", label: "Empty apartment", category: "pricing", valueType: "boolean" },
    { key: "heavyLimescale", label: "Heavy limescale", category: "pricing", valueType: "boolean" },
    { key: "heavyDirt", label: "Heavy dirt", category: "pricing", valueType: "boolean" },
    { key: "insideCabinets", label: "Inside cabinets", category: "pricing", valueType: "boolean" },
    { key: "fridgeCleaning", label: "Fridge cleaning", category: "pricing", valueType: "boolean" },
    { key: "ovenCleaning", label: "Oven cleaning", category: "pricing", valueType: "boolean" },
    { key: "windowsInside", label: "Windows (inside)", category: "pricing", valueType: "boolean" },
    { key: "balconyIncluded", label: "Balcony", category: "pricing", valueType: "boolean" },
  ],
  airbnb_turnover: [
    { key: "propertySizeM2", label: "Property size (m²)", category: "pricing", valueType: "number" },
    { key: "bedroomsCount", label: "Bedrooms", category: "pricing", valueType: "number" },
    { key: "bathroomsCount", label: "Bathrooms", category: "pricing", valueType: "number" },
    { key: "linenChange", label: "Linen change", category: "cleaner", valueType: "boolean" },
    { key: "towelsChange", label: "Towels change", category: "cleaner", valueType: "boolean" },
    { key: "laundryRequired", label: "Laundry required", category: "cleaner", valueType: "boolean" },
    { key: "consumablesRestock", label: "Consumables restock", category: "cleaner", valueType: "boolean" },
    { key: "photoReportRequired", label: "Photo report", category: "cleaner", valueType: "boolean" },
    { key: "checkInTime", label: "Check-in time", category: "cleaner", valueType: "string" },
    { key: "checkOutTime", label: "Check-out time", category: "cleaner", valueType: "string" },
    { key: "keysLocation", label: "Keys location", category: "cleaner", valueType: "string" },
    { key: "specialTurnoverNotes", label: "Turnover notes", category: "cleaner", valueType: "string" },
  ],
  office_cleaning: [
    { key: "officeSizeM2", label: "Office size (m²)", category: "pricing", valueType: "number" },
    { key: "workstationsCount", label: "Workstations", category: "pricing", valueType: "number" },
    { key: "meetingRoomsCount", label: "Meeting rooms", category: "pricing", valueType: "number" },
    { key: "bathroomsCount", label: "Bathrooms", category: "pricing", valueType: "number" },
    { key: "kitchenArea", label: "Kitchen area", category: "cleaner", valueType: "boolean" },
    { key: "frequency", label: "Frequency", category: "pricing", valueType: "string" },
    { key: "afterHours", label: "After hours", category: "pricing", valueType: "boolean" },
    { key: "trashRemoval", label: "Trash removal", category: "cleaner", valueType: "boolean" },
    { key: "suppliesRestock", label: "Supplies restock", category: "cleaner", valueType: "boolean" },
  ],
  dry_cleaning: [
    { key: "sofasCount", label: "Sofas", category: "pricing", valueType: "number" },
    { key: "mattressesCount", label: "Mattresses", category: "pricing", valueType: "number" },
    { key: "carpetsCount", label: "Carpets", category: "pricing", valueType: "number" },
    { key: "carpetAreaM2", label: "Carpet area (m²)", category: "pricing", valueType: "number" },
    { key: "chairsCount", label: "Chairs", category: "pricing", valueType: "number" },
    { key: "materialNotes", label: "Material notes", category: "cleaner", valueType: "string" },
    { key: "stainsDescription", label: "Stains", category: "cleaner", valueType: "string" },
    { key: "petStains", label: "Pet stains", category: "pricing", valueType: "boolean" },
    { key: "elevatorAvailable", label: "Elevator available", category: "cleaner", valueType: "boolean" },
  ],
  window_cleaning: [
    { key: "windowsCount", label: "Windows", category: "pricing", valueType: "number" },
    { key: "windowSashesCount", label: "Window sashes", category: "pricing", valueType: "number" },
    { key: "balconyDoorsCount", label: "Balcony doors", category: "pricing", valueType: "number" },
    { key: "outsideAccess", label: "Outside access", category: "cleaner", valueType: "boolean" },
    { key: "ladderRequired", label: "Ladder required", category: "cleaner", valueType: "boolean" },
    { key: "frameCleaning", label: "Frame cleaning", category: "cleaner", valueType: "boolean" },
    { key: "blindsCleaning", label: "Blinds cleaning", category: "pricing", valueType: "boolean" },
    { key: "interiorOnly", label: "Interior only", category: "cleaner", valueType: "boolean" },
    { key: "highRise", label: "High rise", category: "pricing", valueType: "boolean" },
  ],
  special_pet_package: [
    { key: "packageFocus", label: "Package focus", category: "general", valueType: "string" },
    { key: "allergyFriendlyProducts", label: "Allergy-friendly products", category: "cleaner", valueType: "boolean" },
    { key: "petAreaDescription", label: "Pet area", category: "cleaner", valueType: "string" },
    { key: "hasPets", label: "Pets on site", category: "pricing", valueType: "boolean" },
    { key: "petTypes", label: "Pet types", category: "cleaner", valueType: "string" },
  ],
};
