export const compareRu: Record<string, string> = {
  "public.compare.profile.home_reset.title":"Home Reset",
  "public.compare.profile.home_reset.tagline":"Глубокое обновление всей квартиры",
  "public.compare.profile.home_reset.shortDescription":"Тщательная уборка, когда обычного поддержания чистоты уже недостаточно: особое внимание уделяется налёту, углам и поверхностям, которых часто касаются.",
  "public.compare.profile.move_out.title":"Уборка при переезде",
  "public.compare.profile.move_out.tagline":"Чистота для уверенной передачи квартиры",
  "public.compare.profile.move_out.shortDescription":"Финальная уборка пустой или почти пустой квартиры: кухня, техника, шкафы и санузлы готовы к приёмке.",
  "public.compare.profile.regular_cleaning.title":"Home Care",
  "public.compare.profile.regular_cleaning.tagline":"Регулярная чистота без лишних забот",
  "public.compare.profile.regular_cleaning.shortDescription":"Поддерживающая уборка ухоженной квартиры по удобному еженедельному или ежемесячному графику.",

  "public.compare.profile.home_reset.kitchen.title":"Кухня", "public.compare.profile.home_reset.bathroom.title":"Ванная", "public.compare.profile.home_reset.living.title":"Жилые комнаты и спальни",
  "public.compare.profile.move_out.kitchen.title":"Кухня", "public.compare.profile.move_out.bathroom.title":"Ванная", "public.compare.profile.move_out.living.title":"Жилые комнаты и спальни",
  "public.compare.profile.regular_cleaning.kitchen.title":"Кухня", "public.compare.profile.regular_cleaning.bathroom.title":"Ванная", "public.compare.profile.regular_cleaning.living.title":"Жилые комнаты и спальни",

  "public.compare.profile.home_reset.kitchen.item1":"Столешницы, фартук и доступные поверхности", "public.compare.profile.home_reset.kitchen.item2":"Мойка и смеситель — удаление налёта", "public.compare.profile.home_reset.kitchen.item3":"Техника снаружи и обезжиривание загрязнённых мест", "public.compare.profile.home_reset.kitchen.item4":"Фасады и ручки шкафов", "public.compare.profile.home_reset.kitchen.item5":"Пылесос, мытьё пола и краёв",
  "public.compare.profile.home_reset.bathroom.item1":"Унитаз внутри и снаружи", "public.compare.profile.home_reset.bathroom.item2":"Душ, ванна и стекло — удаление налёта", "public.compare.profile.home_reset.bathroom.item3":"Раковина, смесители и зеркало", "public.compare.profile.home_reset.bathroom.item4":"Доступная плитка и швы", "public.compare.profile.home_reset.bathroom.item5":"Мытьё пола и краёв",
  "public.compare.profile.home_reset.living.item1":"Удаление пыли с доступных поверхностей и декора", "public.compare.profile.home_reset.living.item2":"Пылесос ковров и мягкой мебели по поверхности", "public.compare.profile.home_reset.living.item3":"Мытьё пола и плинтусов", "public.compare.profile.home_reset.living.item4":"Двери, выключатели и ручки", "public.compare.profile.home_reset.living.item5":"Смена постельного белья и лёгкое наведение порядка",
  "public.compare.profile.home_reset.included1":"Тщательное удаление пыли", "public.compare.profile.home_reset.included2":"Глубокая уборка кухни и ванной", "public.compare.profile.home_reset.included3":"Пылесос и мытьё полов", "public.compare.profile.home_reset.included4":"Вынос мусора", "public.compare.profile.home_reset.included5":"Дезинфекция часто используемых поверхностей", "public.compare.profile.home_reset.included6":"Средства, безопасные для питомцев, по запросу",

  "public.compare.profile.move_out.kitchen.item1":"Все поверхности, фартук и пустые шкафы внутри", "public.compare.profile.move_out.kitchen.item2":"Мойка, смесители и зона мусора", "public.compare.profile.move_out.kitchen.item3":"Пустые духовка и холодильник внутри", "public.compare.profile.move_out.kitchen.item4":"Плита, вытяжка и техника снаружи", "public.compare.profile.move_out.kitchen.item5":"Обезжиривание и мытьё пола и углов",
  "public.compare.profile.move_out.bathroom.item1":"Глубокая уборка унитаза", "public.compare.profile.move_out.bathroom.item2":"Душ, ванна, плитка и силиконовые швы", "public.compare.profile.move_out.bathroom.item3":"Раковина, зеркало и смесители", "public.compare.profile.move_out.bathroom.item4":"Доступные вентиляционные решётки", "public.compare.profile.move_out.bathroom.item5":"Пол и зоны брызг на стенах",
  "public.compare.profile.move_out.living.item1":"Все доступные поверхности и выступы", "public.compare.profile.move_out.living.item2":"Пустые шкафы внутри", "public.compare.profile.move_out.living.item3":"Подоконники и стёкла изнутри", "public.compare.profile.move_out.living.item4":"Двери, рамы и плинтусы", "public.compare.profile.move_out.living.item5":"Пылесос и мытьё полов во всех комнатах",
  "public.compare.profile.move_out.included1":"Чек-лист для передачи квартиры", "public.compare.profile.move_out.included2":"Кухня и ванная готовы к приёмке", "public.compare.profile.move_out.included3":"Пустые шкафы внутри", "public.compare.profile.move_out.included4":"Пустая техника внутри", "public.compare.profile.move_out.included5":"Полы во всех комнатах", "public.compare.profile.move_out.included6":"Вынос мусора и финальное наведение порядка",

  "public.compare.profile.regular_cleaning.kitchen.item1":"Столешницы и поверхности", "public.compare.profile.regular_cleaning.kitchen.item2":"Чистка мойки", "public.compare.profile.regular_cleaning.kitchen.item3":"Техника снаружи", "public.compare.profile.regular_cleaning.kitchen.item4":"Пылесос и мытьё пола", "public.compare.profile.regular_cleaning.kitchen.item5":"Вынос мусора",
  "public.compare.profile.regular_cleaning.bathroom.item1":"Чистка унитаза", "public.compare.profile.regular_cleaning.bathroom.item2":"Душ и ванна", "public.compare.profile.regular_cleaning.bathroom.item3":"Раковина и смесители", "public.compare.profile.regular_cleaning.bathroom.item4":"Чистка зеркала", "public.compare.profile.regular_cleaning.bathroom.item5":"Мытьё пола",
  "public.compare.profile.regular_cleaning.living.item1":"Удаление пыли с доступных поверхностей", "public.compare.profile.regular_cleaning.living.item2":"Пылесос", "public.compare.profile.regular_cleaning.living.item3":"Мытьё полов", "public.compare.profile.regular_cleaning.living.item4":"Протирание видимых поверхностей", "public.compare.profile.regular_cleaning.living.item5":"Смена постельного белья по запросу",
  "public.compare.profile.regular_cleaning.included1":"Удаление пыли", "public.compare.profile.regular_cleaning.included2":"Пылесос", "public.compare.profile.regular_cleaning.included3":"Уборка ванной", "public.compare.profile.regular_cleaning.included4":"Поверхности на кухне", "public.compare.profile.regular_cleaning.included5":"Мытьё полов", "public.compare.profile.regular_cleaning.included6":"Вынос мусора",
};
